### ISSUE TITLE
Deduplicate news entries

### ISSUE THREAD

**Issue by jans23** [owncloud/news#465]
I subscribed several feeds from a single newspaper such as "headlines", "politics", "business" etc. It often happens that a single article is published within 2 or 3 of these categories so that it is displayed by New App multiple times. It would be great if the News App would remove such redundancy and display such news only once. Thanks a lot!

PS: For instance Thunderbird RSS reader does avoid such redundancy.

**Comment by Bubbelb** [comment]
Just an idea to simplify things (I hope...):
What if a user can group sumular feeds and see it as a "master feed", or a sub-folder for that matter and let the user set an option on the "master feed" node to simply delete duplicate headlines, or show only the latest headline and discard other (similar) headlines?

**Comment by hochwasser** [comment]
@BernhardPosselt 
I thought about this.
The guid is probably not the right thing. It could be an option for a server with multiple feeds.
What could work: to use the target link of the entry to disambiguate the posts.

**Comment by jans23** [comment]
Sounds like a reasonable approach. This issue is very annoying for me.
It would be great if somebody could start working on it... 

Am 19.11.2015 10:59, schrieb hochwasser: 

> @BernhardPosselt [1] 
> I thought about this.
> The guid is probably not the right thing. It could be an option for a server with multiple feeds.
> What could work: to use the target link of the entry to disambiguate the posts. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/BernhardPosselt
[2] https://github.com/owncloud/news/issues/465#issuecomment-158009530

**Comment by BernhardPosselt** [comment]
@hochwasser that leads to duplicate starred entries.

**Comment by BernhardPosselt** [comment]
And if a folder contains those feeds, each item may show up multiple times.

**Comment by BernhardPosselt** [comment]
What could work is that only mark read/unread will be executed on all items with the same link version.

**Comment by BernhardPosselt** [comment]
Starting with the next version, a fingerprint will be generated over each item: https://github.com/owncloud/news/blob/master/db/item.php#L224

This can be used in the future to search for similar articles (same title, link and body), however this will not fix this issue, merely mark the first step towards fixing it.

**Comment by hochwasser** [comment]
@BernhardPosselt 
This 'mark read/unread' sounds like an interesting idea. Or to fold those entries. Then the user can click on them to read them or scroll over.
I doubt that  a fingerprint is the solution.

**Comment by BernhardPosselt** [comment]
@hochwasser yep, like mentioned the fingerprint is just an md5 hash over title, link and body which can be used to detect duplicate entries.

In general the only solution I see is to adjust this on database level, everything else will probably lessen the pain but spawn more issues.

**Comment by BernhardPosselt** [comment]
Just thought of another thing: if two items are merged, its impossible to update them properly because you are lacking the guid

**Comment by BernhardPosselt** [comment]
So probably mark read/unread should always act on the fingerprint and when selecting articles we should use a SELECT DISTINCT fingerprint to filter out duplicates in a stream

**Comment by BernhardPosselt** [comment]
Ok, I think it is clear how this should be solved now :)

TODOs:
* [ ] Add the enclosure link to the fingerprint
* [ ] Make it possible to run the search indices generation from the admin section
* [ ] On upgrade, use an SQL query to determine if there are empty fingperprints and search indices and warn the user to run it from the command line or admin interface (admin interface can time out, prefer command line)
*  [ ] Modify the mark read and mark all read methods on the ItemMapper class to UNION rows with similar fingerprint
* [ ] Make sure to update the last modified date on the items that are marked read
* [ ] Modify the select all items lookup to use DISTINCT to filter out duplicate entries

**Comment by BernhardPosselt** [comment]
Progress report on this:
* Work is done in the dedup branch
* I've modified the readFeed method that it works like intended. However there are problems with MySql and Postgres: in MySql you can't use subselects on the table to update but you can use joins, on Postgres and Sqlite it's the other way round. This means that all the update queries for marking stuff read (which are already complicated as fuck) need to be rewritten for MySql
* Current way of setting up fixtures is a pain, tests are harder to write which blocks this issue.

I've pushed this back on my priority list, don't expect anything any time soon.

**Comment by BernhardPosselt** [comment]
Implemented this today in the following way:
* Marking a feed or folder as read will not search for duplicates in them and mark them as read in other feeds/folders since this is usually not what you want
* However if you read your feed and items are marked read or you explicitely mark an item as read by clicking on it/via the API, all your duplicate items are marked as read.

**Comment by jans23** [comment]
I can confirm that the implementation works. However, it doesn't solve the actual problem. The two feeds which I subscribed publish the identical article at the same time. Hence, in the owncloud news reader most identical articles are listed next to each other (or at least very near to each other). The implemented change only applies when identical articles are not listed next to each other _and_ when I sync my news app to the server in between. This is hardly the case for me and if it applies, only one or two articles may be affected.
The issue would be solved for me if the server identifies identical articles _upfront_ (before they are displayed and marked as read) and displays only one to me. For instance one article may be marked "read" already while the other is left "unread".

**Comment by BernhardPosselt** [comment]
You mean in folder or all articles view?

**Comment by jans23** [comment]
In all unread articles view.

**Comment by BernhardPosselt** [comment]
I see :)

This should be solvable very easily now that I think about it: when fetching JSON from the server we simply drop all articles whose fingerprint exists already in the articles list. 

However this will have to be implemented on mobile clients as well, I'll update the API items to also include it.

The thing is: if we truly filter out duplicates this will mean trouble in many different ways (stuff like catching updates reliably will be impossible for instance) however only displaying one is an awesome idea. Will fix asap :)

**Comment by jans23** [comment]
> However this will have to be implemented on mobile clients as well,
I'm afraid to wait another year or so to get this implemented by the Android news app. :-( Any option to implement this server-side only? Maybe do the duplication-check right after fetching the actual feeds (instead of when fetching JSON).

**Comment by BernhardPosselt** [comment]
That would be lying to the API. Apart from that Mysql/Posgres compatibility on this is incredibly hard

**Comment by BernhardPosselt** [comment]
Basically filtering out duplicates for mobile apps will remove entries from certain feeds altogether. Feed1 may have some articles that Feed2 does not.

**Comment by BernhardPosselt** [comment]
Can you check if this works as expected in master?

**Comment by BernhardPosselt** [comment]
You will need to run make, see https://github.com/owncloud/news/blob/master/CONTRIBUTING.md#how-to-set-up-a-development-environment

**Comment by jans23** [comment]
Ok, will try when I find time in a few days.

**Comment by BernhardPosselt** [comment]
Ok, if it takes you that long, let's just release a new version :) (done)

**Comment by jans23** [comment]
I can confirm that it works for the Web-based Newsreader. Great. Thank
you very much. Could you help to submit a ticket to the other news
readers? What exactly do they need to do?

Am 12.04.2016 23:23, schrieb Bernhard Posselt:

> Ok, if it takes you that long, let's just release a new version :) (done) 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1] https://github.com/owncloud/news/issues/465#issuecomment-209108606

**Comment by BernhardPosselt** [comment]
Can you take care of that? There's a new fingerprint field for items. If it is the same as an other item, it means both items have the same content. It's in the docs ;)

**Comment by jans23** [comment]
I submitted issue tickets for [Android](https://github.com/owncloud/News-Android-App/issues/513) and [iOS](https://github.com/owncloud/news-iOS-App/issues/71) news app.
